In [5]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\santa\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


# CREATING TENSORS

1. 1 DIMENTSIONAL TENSORS: these are single digits and can be referred to a scalars or rank 0 tensors. Rank 0 because of the computers zero index counting i will guess. we will see these when we get to checking the ranks and degrees of tensors.

In [20]:
myname = tf.Variable('Theo Caesar', tf.string)
myage = tf.Variable(48, tf.int32) #INT8, 16,32, 64
myheight = tf.Variable(5.10, tf.float64) #FLOAT 32, 64

In [21]:
name = tf.Variable(['Theophilus', 'Ofoe', 'Caesar'],tf.string) #3 values in 1d-1 array with 3vals 
#which can add to any time and not affect the dimension of the tensor

fullname = tf.Variable([['Theo'], ['Caesar']], tf.string) #single values in two dim tensors--we can
# still add to these nested lists any number of strings seperated by commas and still not alter
# the dim of our fullname tensor-until we add another nested list. NB: size of both nested list 
# should be equal at all times

ournames = tf.Variable([['Theo', 'Ofoe', 'Caesar'], #three values in 3 dim tensors
                        ['Bryan', 'OO Borbor', 'Caesar'], 
                        ['Ezekiel', 'Alamu', 'Caesar']          
                       ] , tf.string)

### Rank/Degree of tensors: this refers to the num of dimensions in a tensor. as stated earlier, the above code is a rank 0 tensor known as scalar as it has just a single dimension.

In [22]:
tf.rank(myname)#should return 0--hack:we have no array


<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [23]:
tf.rank(name)#should return 1--hack:we have 1 array


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [24]:
tf.rank(fullname)#should return 2--hack:we have 2 nested arrays


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [25]:
tf.rank(ournames)#should return 3--hack:we've 3 nested arrays however it only returned 2; perhaps its cap

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of a tensor: applied as an attribute to a tensor

In [26]:
myname.shape #zero dim with no arrays

TensorShape([])

In [27]:
name.shape #1dim array with 3 names(data)

TensorShape([3])

In [28]:
fullname.shape #2dim array with 1 name in each

TensorShape([2, 1])

In [29]:
ournames.shape #3dim array with 3 names in each...mais rank is cappeed at 2

TensorShape([3, 3])

### Reshaping Tensors
the number of elements in a tensor is eqult to the product fo the sizes of all its shapes. there are often many shapes that have the same number of elements, making it convenient to be able to change tensor shape.

In [30]:
mytensor = tf.ones([1,2,3]) # ones method creates a shape of the passed array value full of ones as nums in 
                            #the shape 1 array, with 2 nested array with 3 values in each nesteed array
    
mytensorV2 = tf.reshape(mytensor, [2, 3, 1])#, reshape my tensor into 2 arrays/lists with 3 nested arrays
                                            # or list of 1 digit only
    
mytensorV3 = tf.reshape(mytensorV2, [3, -1]) # neg 1 makes sys infer what the dimension(nested list should be)

# and remember the elements in a tensor should always be equal to the product of nums in our shape

In [33]:
print('mytensor ==>',mytensor,'\n')
print('mytensor2  [2, 3, 1])==>',mytensorV2,'\n')
print('mytensor3 [3, -1]) ==>',mytensorV3,'\n')

mytensor ==> tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32) 

mytensor2  [2, 3, 1])==> tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) 

mytensor3 [3, -1]) ==> tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) 

